// <auto-generated />
using System;
using LGPD_MDE.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LGPD_MDE.Migrations
{
    [DbContext(typeof(LgpdDbContext))]
    [Migration("20220621195310_criacao")]
    partial class criacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Areas")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("AREAS");

                    b.HasKey("Id");

                    b.ToTable("AREA", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("EnterpriseCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ENTERPRISE_CATEGORY_ID");

                    b.Property<int?>("EnterpriseCategoryId1")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FIELD_ID");

                    b.Property<int?>("FieldId1")
                        .HasColumnType("int");

                    b.Property<float>("Maturity")
                        .HasColumnType("FLOAT")
                        .HasColumnName("MATURITY");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("DATE")
                        .HasColumnName("MATURITY_DATE");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("MOBILE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("ProgrectionStartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("PROGRECTION_START_DATE");

                    b.Property<ulong>("ProgrectionStatus")
                        .HasColumnType("BIT")
                        .HasColumnName("PROGRECTION_STATUS");

                    b.Property<float>("Progress")
                        .HasColumnType("FLOAT")
                        .HasColumnName("PROGRESS");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QUESTION_ID");

                    b.Property<int?>("QuestionId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("DATE")
                        .HasColumnName("REGISTRATION_DATE");

                    b.Property<int>("ReportPeriodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("REPORT_PERIOD_ID");

                    b.Property<int?>("ReportPeriodId1")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("SITE");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseCategoryId");

                    b.HasIndex("EnterpriseCategoryId1");

                    b.HasIndex("FieldId");

                    b.HasIndex("FieldId1");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId1");

                    b.HasIndex("ReportPeriodId");

                    b.HasIndex("ReportPeriodId1");

                    b.HasIndex("WorkshopId");

                    b.ToTable("ENTERPRISE", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.EnterpriseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("CATEGORY");

                    b.HasKey("Id");

                    b.ToTable("ENTERPRISE_CATEGORY", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("FIELDS");

                    b.HasKey("Id");

                    b.ToTable("FIELD", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Impact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Impacts")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("IMPACTS");

                    b.HasKey("Id");

                    b.ToTable("IMPACT", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Probability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Probabilitys")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("PROBABILITYS");

                    b.HasKey("Id");

                    b.ToTable("PROBABILITY", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ACTION");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AREA_ID");

                    b.Property<int?>("AreaId1")
                        .HasColumnType("int");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("EFFECT");

                    b.Property<int>("ImpactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IMPACT_ID");

                    b.Property<int?>("ImpactId1")
                        .HasColumnType("int");

                    b.Property<int>("ProbabilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROBABILITY_ID");

                    b.Property<int?>("ProbabilityId1")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QUESTION_CATEGORY_ID");

                    b.Property<int?>("QuestionCategoryId1")
                        .HasColumnType("int");

                    b.Property<ulong>("RepliedStatus")
                        .HasColumnType("BIT")
                        .HasColumnName("REPLIED_STATUS");

                    b.Property<int>("Reply")
                        .HasColumnType("INTEGER")
                        .HasColumnName("REPLY");

                    b.Property<ulong>("SuitableStatus")
                        .HasColumnType("BIT")
                        .HasColumnName("SUITABLE_STATUS");

                    b.Property<string>("Wording")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("WORDING");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AreaId1");

                    b.HasIndex("ImpactId");

                    b.HasIndex("ImpactId1");

                    b.HasIndex("ProbabilityId");

                    b.HasIndex("ProbabilityId1");

                    b.HasIndex("QuestionCategoryId");

                    b.HasIndex("QuestionCategoryId1");

                    b.ToTable("QUESTION", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.QuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("CATEGORY");

                    b.HasKey("Id");

                    b.ToTable("QUESTION_CATEGORY", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.ReportPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("PERIOD");

                    b.HasKey("Id");

                    b.ToTable("REPORT_PERIOD", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("RISKS");

                    b.HasKey("Id");

                    b.ToTable("RISK", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("FUNCTION");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("MOBILE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("USER");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(100)
                        .HasColumnType("DATE")
                        .HasColumnName("DATE");

                    b.Property<string>("MeetingLink")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("MEETING_LINK");

                    b.HasKey("Id");

                    b.ToTable("WORKSHOP", (string)null);
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Enterprise", b =>
                {
                    b.HasOne("LGPD_MDE.Entities.Generated.EnterpriseCategory", "EnterpriseCategory")
                        .WithMany()
                        .HasForeignKey("EnterpriseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.EnterpriseCategory", null)
                        .WithMany("Enterprise")
                        .HasForeignKey("EnterpriseCategoryId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.Field", null)
                        .WithMany("Enterprise")
                        .HasForeignKey("FieldId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.Question", null)
                        .WithMany("Enterprise")
                        .HasForeignKey("QuestionId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.ReportPeriod", "ReportPeriod")
                        .WithMany()
                        .HasForeignKey("ReportPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.ReportPeriod", null)
                        .WithMany("Enterprise")
                        .HasForeignKey("ReportPeriodId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.Workshop", "Workshop")
                        .WithMany("Enterprise")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseCategory");

                    b.Navigation("Field");

                    b.Navigation("Question");

                    b.Navigation("ReportPeriod");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Question", b =>
                {
                    b.HasOne("LGPD_MDE.Entities.Generated.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.Area", null)
                        .WithMany("Question")
                        .HasForeignKey("AreaId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.Impact", "Impact")
                        .WithMany()
                        .HasForeignKey("ImpactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.Impact", null)
                        .WithMany("Question")
                        .HasForeignKey("ImpactId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.Probability", "Probability")
                        .WithMany()
                        .HasForeignKey("ProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.Probability", null)
                        .WithMany("Question")
                        .HasForeignKey("ProbabilityId1");

                    b.HasOne("LGPD_MDE.Entities.Generated.QuestionCategory", "QuestionCategory")
                        .WithMany()
                        .HasForeignKey("QuestionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LGPD_MDE.Entities.Generated.QuestionCategory", null)
                        .WithMany("Question")
                        .HasForeignKey("QuestionCategoryId1");

                    b.Navigation("Area");

                    b.Navigation("Impact");

                    b.Navigation("Probability");

                    b.Navigation("QuestionCategory");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Area", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.EnterpriseCategory", b =>
                {
                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Field", b =>
                {
                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Impact", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Probability", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Question", b =>
                {
                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.QuestionCategory", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.ReportPeriod", b =>
                {
                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("LGPD_MDE.Entities.Generated.Workshop", b =>
                {
                    b.Navigation("Enterprise");
                });
#pragma warning restore 612, 618
        }
    }
}
